# Generated by Django 4.0.6 on 2024-06-06 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_order_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='profit',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
