# Generated by Django 4.0.6 on 2024-06-12 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_category_cateimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='amount',
            field=models.DecimalField(decimal_places=0, default='0', max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='bKash',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='reference',
            field=models.CharField(default='0', max_length=255),
        ),
    ]
