# Generated by Django 4.0.6 on 2025-03-18 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_order_amount_order_bkash_order_reference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='imgbb_url',
        ),
        migrations.RemoveField(
            model_name='category',
            name='imgbb_url',
        ),
        migrations.RemoveField(
            model_name='image',
            name='imgbb_url',
        ),
    ]
