# Generated by Django 4.0.6 on 2024-06-06 07:33

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_us', tinymce.models.HTMLField()),
                ('about_us', tinymce.models.HTMLField()),
                ('privacy_policy', tinymce.models.HTMLField()),
            ],
        ),
    ]
